
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: secure_area
    user_class: Security\UserBundle\Entity\User
    registration:

        form:
            type: registration_form
            validation_groups: [SecurityRegistration]
        confirmation:
            enabled:    false # change to true for required email confirmation

hwi_oauth:
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_name: secure_area
    connect:
        confirmation: true
        account_connector: my_user_provider
        registration_form_handler: hwi_oauth.registration.form.handler.fosub_bridge
        registration_form: fos_user.registration.form

    resource_owners:
        facebook:
            type:                facebook
            client_id:           1085320454858054
            client_secret:       83626f1517c299dfa715cea0ec2f9e3f
            scope:               "email"
            paths:
                email:           email

    fosub:
        # try 30 times to check if a username is available (foo, foo1, foo2 etc)
        username_iterations: 30

        # mapping between resource owners (see below) and properties
        properties:
            facebook: facebook_id