parameters:
    my_user_provider.class: Security\UserBundle\Security\Core\User\FOSUBUserProvider

services:
    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{facebook: facebook_id}]

    app.form.registration:
        class: Security\UserBundle\Form\RegisterFormType
        arguments: [@fos_user.user_manager,{facebook: facebook_id}]
        tags:
            - { name: form.type, alias: registration_form }

    app.user.provider:
        class: Security\UserBundle\Security\Core\User\FOSUBUserProvider
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - 'Security\UserBundle\Entity\User'

    # authentication event listener
    acme.security.authentication_failure_event_listener:
        class: Security\UserBundle\EventListener\AuthenticationListener
        arguments: [ @doctrine.orm.default_entity_manager, @request_stack ]
        tags:
            - { name: kernel.event_listener, event: security.authentication.failure, method: onAuthenticationFailure }
            - { name: kernel.event_listener, event: security.interactive_login, method: onAuthenticationSuccess }

